spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    druid:
      aop-patterns: com.kuhn.springboot.*  #监控springBean
      filter:     #底层开启功能  stat(sql监控)   wall(防火墙)
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true

        wall:
          enabled: true
          config:
            drop-table-allow: false

      stat-view-servlet:    #配置监控页功能
        login-password: admin
        login-username: admin
        enabled: true
        reset-enable: false

      web-stat-filter:    #监控web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

  jdbc:
    template:
      query-timeout: 3

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true    #开启下划线转驼峰


#management 是actuator的所有配置
management:
  endpoints:
    enabled-by-default: true    #默认开启所有监控端点
    web:
      exposure:
        include: '*'    #以web方式暴露所有端点
